apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabstergoCorp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergoCorp
  template:
    metadata:
      labels:
        app: abstergoCorp
    spec:
      containers:
      - name: train-schedule
        image: shakuntala22/abstergoCorp:latest
        ports:
        - containerPort: 3000
